### ISSUE TITLE
ionic 3 - install pesdk in ios

### ISSUE THREAD

**Issue by alexwar** [imgly/pesdk-cordova-demo#11]
I'm trying to install pesdk according to your example, but when trying to install a plugin I get such a bug:
```
MacBook-Pro-Mac:PESDKDemo mac$ ionic cordova plugin add ../pesdk-cordova-demo/ --nofetch
> cordova plugin add ../pesdk-cordova-demo/ --save
Installing "cordova-plugin-pesdk" for android

Installing "cordova-plugin-add-swift-support" for android

Android Studio project detected

Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-pesdk" for ios

Plugin dependency "cordova-plugin-add-swift-support@1.7.1" already fetched, using that version.

Dependent plugin "cordova-plugin-add-swift-support" already installed on ios.

Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-pesdk': CordovaError: Uh oh!
Cannot find framework "/Users/mac/git/PESDKDemo/plugins/cordova-plugin-pesdk/src/ios/PhotoEditorSDK.framework" for plugin cordova-plugin-pesdk in iOS platform
    at install (/Users/mac/git/PESDKDemo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:109:48)
    at ActionStack.process (/Users/mac/git/PESDKDemo/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/mac/git/PESDKDemo/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/mac/git/PESDKDemo/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/mac/git/PESDKDemo/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)

(node:13014) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Uh oh!
Cannot find framework "/Users/mac/git/PESDKDemo/plugins/cordova-plugin-pesdk/src/ios/PhotoEditorSDK.framework" for plugin cordova-plugin-pesdk in iOS platform
(node:13014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also when I try to execute the command to get the repository by the specified program, I get the same error, so I used the command specified by the following

```
MacBook-Pro-Mac:~ mac$ git submodule add git@github.com:imgly/pesdk-cordova-demo.git 
Cloning into '/Users/mac/pesdk-cordova-demo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:imgly/pesdk-cordova-demo.git' into submodule path '/Users/mac/pesdk-cordova-demo' failed
```
I used this command to work around the error
git submodule add https://github.com/imgly/pesdk-cordova-demo.git

I read this decision, but I did not quite understand it.
https://github.com/imgly/pesdk-cordova-demo/issues/2

**Comment by alexwar** [comment]
Последний iOS SDK необходимо загрузить вручную из нашего репозитория и поместить в /src/ios/каталог.
все нашел... закрываю тему

**Comment by uklawitter** [comment]
Hi! I get the same error. Could you explain where you download your latest SDK? Maybe the repository could be updated also?!?

**Comment by uklawitter** [comment]
Okay, I guess this is the URL for the latest iOS SDK:
https://github.com/imgly/pesdk-ios-build/releases
