### ISSUE TITLE
Error when trying to add plugin

### ISSUE THREAD

**Issue by ir2pid** [imgly/pesdk-cordova-demo#14]
I get the following error when running

> ionic cordova plugin add ../pesdk-cordova-demo --nofetch --verbose

```
Installing "cordova-plugin-add-swift-support" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-pesdk': CordovaError: Uh oh!
Cannot find framework "xx/photoeditorsdk/PESDKDemo/plugins/cordova-plugin-pesdk/src/ios/PhotoEditorSDK.framework" for plugin cordova-plugin-pesdk in iOS platform
    at install (xx/photoeditorsdk/PESDKDemo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:109:48)
    at ActionStack.process (xx/photoeditorsdk/PESDKDemo/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (xx/photoeditorsdk/PESDKDemo/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (xx/photoeditorsdk/PESDKDemo/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (xx/photoeditorsdk/PESDKDemo/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/Users/xx/.nvm/versions/node/v10.14.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/xx/.nvm/versions/node/v10.14.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/Users/xx/.nvm/versions/node/v10.14.0/lib/node_modules/cordova/node_modules/q/q.js:854:54)
    at /Users/xx/.nvm/versions/node/v10.14.0/lib/node_modules/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/xx/.nvm/versions/node/v10.14.0/lib/node_modules/cordova/node_modules/q/q.js:816:13)
Uh oh!
Cannot find framework "xx/photoeditorsdk/PESDKDemo/plugins/cordova-plugin-pesdk/src/ios/PhotoEditorSDK.framework" for plugin cordova-plugin-pesdk in iOS platform
[ERROR] An error occurred while running subprocess cordova.
    cordova plugin add ../pesdk-cordova-demo --save exited with exit code 1.
    
    Re-running this command with the --verbose flag may provide more information.
```

**Comment by maltebaumann** [comment]
Hey ir2pid, as stated in the README, you need to manually download the iOS SDK and add it to your project as it exceeds GitHub's file size limit:

> :warning: The latest iOS SDK needs to be downloaded manually from [our repository](https://github.com/imgly/pesdk-ios-build/releases) and placed in the `/src/ios/` directory.
