### ISSUE TITLE
Can't add cordova plugin...

### ISSUE THREAD

**Issue by bcrigler** [imgly/pesdk-cordova-demo#22]
```
ionic cordova plugin add ../pesdk-cordova-demo --nofetch --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'plugin', 'add', '../pesdk-cordova-demo' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, nofetch: true, project: null, '--': [] } +5ms
  ionic:lib:project Project type from config: @ionic/angular (angular) +0ms
  ionic:lib:project Project details: { configPath: '/Users/bcrigler/Documents/TIP/PESDK/pesdk-ionic-demo/PESDKDemo/ionic.config.json', errors: [], context: 'app', type: 'angular' } +0ms
  ionic Context: { binPath: '/Users/bcrigler/.nvm/versions/node/v10.16.3/lib/node_modules/ionic/bin/ionic', libPath: '/Users/bcrigler/.nvm/versions/node/v10.16.3/lib/node_modules/ionic', execPath: '/Users/bcrigler/Documents/TIP/PESDK/pesdk-ionic-demo/PESDKDemo', version: '5.4.6' } +0ms
  ionic:lib:integrations:cordova:config Loading Cordova Config (config.xml: '/Users/bcrigler/Documents/TIP/PESDK/pesdk-ionic-demo/PESDKDemo/config.xml', package.json: '/Users/bcrigler/Documents/TIP/PESDK/pesdk-ionic-demo/PESDKDemo/package.json') +0ms
> cordova plugin add ../pesdk-cordova-demo --verbose
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova plugin' [ 'add',
  ionic:lib:telemetry   '../pesdk-cordova-demo',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--nofetch' ] +0ms
No scripts found for hook "before_plugin_add".
No version specified for ../pesdk-cordova-demo, retrieving version from config.xml
No version for null saved in config.xml or package.json
Attempting to use npm info for null to choose a compatible release
Running command: npm view ../pesdk-cordova-demo --json
Command finished with error code 1: npm view,../pesdk-cordova-demo,--json
npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 'PESDKDemo' is not in the npm registry.
npm ERR! 404 name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404  'PESDKDemo@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bcrigler/.npm/_logs/2019-12-19T14_35_40_357Z-debug.log
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 'PESDKDemo' is not in the npm registry.
npm ERR! 404 name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404  'PESDKDemo@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bcrigler/.npm/_logs/2019-12-19T14_35_40_357Z-debug.log
    at ChildProcess.whenDone (/Users/bcrigler/.nvm/versions/node/v10.16.3/lib/node_modules/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add ../pesdk-cordova-demo --verbose exited with exit code 1.
```

**Comment by bcrigler** [comment]
I fixed it... instructions in your docs aren't the clearest but I got it.
